In [13]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import statsmodels.api as sm

from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split

## Dataset 1: Instacart Analysis

In [2]:
data1 = pd.read_csv('https://raw.githubusercontent.com/eghatzis0527/DX699---HW-Assignments/refs/heads/main/instacart.csv')

transform_cols = ['times_purchased', 'num_orders', 'frequency', 'Product Popularity', 'Last Product Order', 'Last Order', 'Orders Since Last Purchase']

for col in transform_cols:
    data1[f'log_{col}'] = np.log1p(data1[col])

data1_transformed = data1.drop(columns = ['times_purchased', 'num_orders', 'frequency', 'Product Popularity', 'Last Product Order', 'Last Order', 'Orders Since Last Purchase'])

data1_transformed.head()

   user_id  product_id  ...  log_Last Order  log_Orders Since Last Purchase
0       71          45  ...        3.178054                        2.708050
1       71         117  ...        3.178054                        0.000000
2       71        2078  ...        3.178054                        3.044522
3       71        2825  ...        3.178054                        2.890372
4       71        3376  ...        3.178054                        1.609438

[5 rows x 10 columns]

In [9]:
X = data1_transformed.drop(columns = ['ordered'])
y = data1_transformed['ordered']

model = LinearRegression()

model.fit(X, y)

model.coef_

array([-1.85844815e-08,  3.30587125e-08,  8.43130152e-02,  1.22894456e-02,
        1.30557690e-02,  5.66384002e-04, -2.88704293e-02,  1.22894456e-02,
       -4.72387383e-02])

In [11]:
X.columns

Index(['user_id', 'product_id', 'log_times_purchased', 'log_num_orders',
       'log_frequency', 'log_Product Popularity', 'log_Last Product Order',
       'log_Last Order', 'log_Orders Since Last Purchase'],
      dtype='str')

In [14]:
cols = X.columns

X_squared = pd.concat((X, (X**2).rename(columns = {f'{var}' : f'{var}2' for var in cols })), axis = 1)
X_squared = sm.add_constant(X_squared)

X_squared.head()

   const  user_id  ...  log_Last Order2  log_Orders Since Last Purchase2
0    1.0       71  ...        10.100026                         7.333536
1    1.0       71  ...        10.100026                         0.000000
2    1.0       71  ...        10.100026                         9.269117
3    1.0       71  ...        10.100026                         8.354249
4    1.0       71  ...        10.100026                         2.590290

[5 rows x 19 columns]

In [15]:
model.fit(X_squared, y)

model.coef_

array([ 0.00000000e+00,  3.00413966e-09,  1.32794771e-13,  2.43269335e-16,
        1.16448815e-15,  7.02029677e-17, -3.12645606e-17,  1.23380940e-15,
        1.16448815e-15,  1.17773090e-15, -9.11942259e-14,  5.83359899e-13,
        1.29659474e-15,  9.86129203e-15,  6.94445174e-17, -1.85792939e-18,
        8.32757908e-15,  9.86129203e-15,  5.72834172e-15])

In [21]:
corr_1 = X_squared.corr(numeric_only = True)

upper_tri = corr_1.where(np.triu(np.ones(corr_1.shape), k = 1).astype(bool))

high_corr = upper_tri.stack().reset_index()
high_corr.columns = ['Variable 1', 'Variable 2', 'Correlation']

corr_tbl_1 = high_corr[high_corr['Correlation'].ge(0.8)]
corr_tbl_1 = corr_tbl_1.sort_values(by = ['Correlation'], ascending = False)

corr_tbl_1

                         Variable 1  ... Correlation
84                   log_num_orders  ...    1.000000
264                 log_num_orders2  ...    1.000000
89                   log_num_orders  ...    0.988527
93                   log_num_orders  ...    0.988527
165                  log_Last Order  ...    0.988527
169                  log_Last Order  ...    0.988527
149          log_Last Product Order  ...    0.977488
69              log_times_purchased  ...    0.969256
29                          user_id  ...    0.969009
49                       product_id  ...    0.968813
189  log_Orders Since Last Purchase  ...    0.946289
109                   log_frequency  ...    0.932337
129          log_Product Popularity  ...    0.912437

[13 rows x 3 columns]

Looking at these results, all of the squared values are highly correlated, but all the engineered features are also highly correlated. This is concerning due to multicollinearity. The engineered features might also be highly correlated since they are built in very similar ways

## Dataset 2: Amazon Reviews Dataset

In [23]:
import ast
from sklearn.preprocessing import MultiLabelBinarizer

small_reviews = pd.read_csv('https://raw.githubusercontent.com/eghatzis0527/DX699---HW-Assignments/refs/heads/main/small_reviews%5B1%5D.csv')

small_meta = pd.read_csv('https://raw.githubusercontent.com/eghatzis0527/DX699---HW-Assignments/refs/heads/main/small_meta%5B1%5D.csv')

small_meta = small_meta.set_index(keys = 'parent_asin')

small_meta = small_meta.drop(columns = ['title', 'images'])

data2 = small_reviews.join(small_meta, on = 'parent_asin', how = 'inner')

data2 = data2.drop(columns = ['main_category', 'store', 'rating_number', 'videos', 'images', 'subtitle', 'author', 'bought_together', 'features', 'description', 'details', 'timestamp', 'text', 'title'])

data2['product_review_count'] = data2.groupby('asin').transform('size')
data2['user_review_count'] = data2.groupby('user_id').transform('size')

data2['price'] = data2['price'].fillna(data2['price'].median())

data2['categories'] = data2['categories'].apply(ast.literal_eval)

mlb = MultiLabelBinarizer()

categories = pd.DataFrame(mlb.fit_transform(data2['categories']), columns = mlb.classes_, index = data2.index)

top_30 = categories.sum().sort_values(ascending = False).head(31).index

categories = categories[top_30[1:31]]

data2 = data2.drop(columns = 'categories')

data2 = data2.join(categories)

columns_to_transform = ['helpful_vote', 'average_rating', 'price', 'product_review_count', 'user_review_count']

for col in columns_to_transform:
    data2[f'log_{col}'] = np.log1p(data2[col])

data2_transformed = data2.drop(columns = ['helpful_vote', 'average_rating', 'price', 'product_review_count', 'user_review_count'])

data2_transformed = data2_transformed.reset_index(drop = True)

for i in range(len(data2_transformed)):
    if data2_transformed.iloc[i]['rating'] == 4:
        data2_transformed.loc[i, 'liked'] = 1
    elif data2_transformed.iloc[i]['rating'] == 5:
        data2_transformed.loc[i, 'liked'] = 1
    else:
        data2_transformed.loc[i, 'liked'] = 0

X = data2_transformed.drop(columns = ['asin', 'parent_asin', 'user_id', 'liked'])
y = data2_transformed['liked']

In [24]:
X.head()

   rating  verified_purchase  ...  log_product_review_count  log_user_review_count
0       5              False  ...                  0.693147               0.693147
1       1               True  ...                  0.693147               0.693147
2       4               True  ...                  0.693147               1.098612
3       5               True  ...                  0.693147               1.098612
4       5               True  ...                  1.609438               0.693147

[5 rows x 37 columns]

In [ ]:
model.fit(X, y)

model.coef_

array([ 0.28319794, -0.00981754,  0.07346078,  0.03150438,  0.02224576,
       -0.19362346, -0.03593603, -0.03095446, -0.02711167, -0.01646754,
        0.01234059,  0.16976443, -0.14671058, -0.03131923, -0.02771575,
        0.01067245, -0.06317729,  0.03860108, -0.00669504,  0.15102118,
       -0.0171856 ,  0.0452093 , -0.04515985,  0.02006723,  0.02006723,
        0.06459393,  0.06371471,  0.06371471, -0.19065059, -0.05069943,
        0.01420402,  0.10095418,  0.01131014,  0.16924854, -0.01189931,
       -0.00131484,  0.00788496])

In [26]:
cols = X.columns

X_squared = pd.concat((X, (X**2).rename(columns = {f'{var}' : f'{var}2' for var in cols })), axis = 1)
X_squared = sm.add_constant(X_squared)

X_squared.head()

   const  rating  ...  log_product_review_count2  log_user_review_count2
0    1.0       5  ...                   0.480453                0.480453
1    1.0       1  ...                   0.480453                0.480453
2    1.0       4  ...                   0.480453                1.206949
3    1.0       5  ...                   0.480453                1.206949
4    1.0       5  ...                   2.590290                0.480453

[5 rows x 75 columns]

In [27]:
model.fit(X_squared, y)

model.coef_

array([-3.09571524e-15,  2.20819904e-01, -7.55412671e-03,  3.19593698e-02,
        1.20387847e-02,  1.08752389e-02, -8.72293697e-02, -1.76735046e-02,
       -1.38377389e-02, -4.76073900e-03, -9.29937569e-03,  7.47257801e-04,
        7.95763609e-02, -6.92761360e-02, -8.31329786e-03, -1.18984893e-02,
        2.39455060e-03, -2.95063723e-02,  1.73983959e-02,  9.90229667e-03,
        6.95272045e-02, -4.12331783e-03,  6.84306436e-03, -2.66273668e-02,
        1.21089381e-02,  1.21089381e-02,  4.46394986e-02,  3.11486378e-02,
        3.11486378e-02, -9.10065653e-02, -1.55206383e-02,  1.40287860e-02,
        5.19381681e-02,  2.62232630e-02,  1.52900678e+00,  1.69367293e-02,
        2.34562328e-01, -2.77761929e-02,  9.53995736e-03, -7.55412671e-03,
        3.19593698e-02,  1.20387847e-02,  1.08752389e-02, -8.72293697e-02,
       -1.76735046e-02, -1.38377389e-02, -4.76073900e-03, -9.29937569e-03,
        7.47257801e-04,  7.95763609e-02, -6.92761360e-02, -8.31329786e-03,
       -1.18984893e-02,  2.39455060e-03, -2.95063723e-02,  1.73983959e-02,
        9.90229667e-03,  6.95272045e-02, -4.12331783e-03,  6.84306436e-03,
       -2.66273668e-02,  1.21089381e-02,  1.21089381e-02,  4.46394986e-02,
        3.11486378e-02,  3.11486378e-02, -9.10065653e-02, -1.55206383e-02,
        1.40287860e-02,  5.19381681e-02, -8.67349380e-03, -4.17784563e-01,
       -5.18681525e-03, -9.73848405e-02,  8.34548157e-03])

In [28]:
corr_2 = X_squared.corr(numeric_only = True)

upper_tri = corr_2.where(np.triu(np.ones(corr_2.shape), k = 1).astype(bool))

high_corr = upper_tri.stack().reset_index()
high_corr.columns = ['Variable 1', 'Variable 2', 'Correlation']

corr_tbl_2 = high_corr[high_corr['Correlation'].ge(0.8)]
corr_tbl_2 = corr_tbl_2.sort_values(by = ['Correlation'], ascending = False)

corr_tbl_2

                 Variable 1           Variable 2  Correlation
189       verified_purchase   verified_purchase2     1.000000
4865  Roasted Coffee Beans2  Whole Coffee Beans2     1.000000
265               Beverages           Beverages2     1.000000
341         Snacks & Sweets     Snacks & Sweets2     1.000000
417          Pantry Staples      Pantry Staples2     1.000000
...                     ...                  ...          ...
839         Breads & Bakery              Cookies     0.850279
1717                Cereals        Cold Cereals2     0.812195
1680                Cereals         Cold Cereals     0.812195
2309           Cold Cereals             Cereals2     0.812195
4492               Cereals2        Cold Cereals2     0.812195

[65 rows x 3 columns]

Again, a lot of the highly correlated features are either features that are duplicates of themselves, the squared version of the feature or the regular features that are correlated. What would be the best move is to remove a lot of the duplicates, and then also figuring out which features should be squares and which should not to prevent multicollinearity.

## Dataset 3: Ecommerce Dataset

In [29]:
data3 = pd.read_csv('/workspaces/DX799---HW-Assignments/data.csv', encoding = 'windows-1252')
data3['Purchased'] = 1

customer_id = data3['Customer ID'].values
segments = data3['Segment'].values
cities = data3['City'].values
state = data3['State'].values
region = data3['Region'].values
product_id = data3['Product ID'].values
categories = data3['Category'].values
subcategories = data3['Sub-Category'].values

def generate_row(df):
    row = {}

    row['Customer ID'] = np.random.choice(customer_id)
    cust_id = row['Customer ID']
    purchased = set(df[df['Customer ID'] == cust_id]['Product ID'])
    candidates = list(set(product_id) - purchased)

    row['Segment'] = np.random.choice(segments)
    row['State'] = np.random.choice(state)
    row['City'] = np.random.choice(cities)
    row['Region'] = np.random.choice(region)
    row['Product ID'] = np.random.choice(candidates)
    row['Category'] = np.random.choice(categories)
    row['Sub-Category'] = np.random.choice(subcategories)

    row['Sales'] = 0
    row['Discount'] = 0
    row['Quantity'] = 0
    row['Profit'] = 0
    row['Purchased'] = 0

    return row

fake_rows = pd.DataFrame([generate_row(data3) for n in range(1000)])

fake_df = pd.concat([data3, fake_rows], ignore_index = True)

fake_df = fake_df.drop(columns = ['Row ID', 'Product Name', 'Country', 'Postal Code', 'Order ID', 'Order Date'])

fake_df_encoded = pd.get_dummies(fake_df, columns = ['Ship Mode', 'Segment', 'State', 'Region', 'Category', 'Sub-Category'], dtype = int)

X = fake_df_encoded.drop(columns = ['Customer ID', 'Product ID', 'City', 'Purchased'])
y = fake_df_encoded['Purchased']

In [30]:
X.head()

     Sales  Quantity  ...  Sub-Category_Supplies  Sub-Category_Tables
0   48.896         4  ...                      0                    0
1  474.430        11  ...                      0                    0
2    3.600         2  ...                      0                    0
3  454.560         5  ...                      0                    0
4  141.420         5  ...                      0                    0

[5 rows x 82 columns]

In [31]:
model.fit(X, y)

model.coef_

array([ 6.48668770e-19, -1.19370659e-16,  1.24900090e-15, -3.29597460e-17,
        1.00000000e+00,  1.00000000e+00,  1.00000000e+00,  1.00000000e+00,
       -3.50136586e-14, -3.51663143e-14, -3.51940699e-14,  1.95538030e-14,
        1.89154248e-14,  1.89293026e-14,  2.02060590e-14,  1.88737914e-14,
        1.84574578e-14,  2.01505479e-14,  1.80966353e-14,  1.98729921e-14,
        1.87350135e-14,  1.89848137e-14,  1.94566585e-14,  1.99770755e-14,
        1.96509475e-14,  2.15244489e-14,  1.94289029e-14,  1.84713356e-14,
        1.85684801e-14,  1.94982919e-14,  2.02060590e-14,  1.91929805e-14,
        1.97064587e-14,  1.95468641e-14,  1.85337856e-14,  2.00117700e-14,
        1.80827575e-14,  1.88252192e-14,  1.81799020e-14,  1.84643967e-14,
        1.86239912e-14,  1.93872696e-14,  1.90143040e-14,  1.86101135e-14,
        1.96440086e-14,  1.92276750e-14,  1.82631688e-14,  1.90594068e-14,
        1.96023753e-14,  2.00534034e-14,  2.01123840e-14,  1.90958360e-14,
        1.89744054e-14,  2.00013617e-14,  1.94982919e-14,  1.99978922e-14,
        1.85598065e-14,  1.99562589e-14,  1.73305814e-13,  1.74360526e-13,
        1.73583370e-13,  1.73971948e-13, -6.54615251e-13, -6.54198917e-13,
       -6.54726273e-13, -4.21884749e-14, -4.17860191e-14, -4.16333634e-14,
       -4.22439861e-14, -4.16888746e-14, -4.17443857e-14, -4.22994972e-14,
       -4.15223411e-14, -4.15500967e-14, -4.19386748e-14, -4.09117185e-14,
       -4.13002965e-14, -4.21884749e-14, -4.17998969e-14, -4.23550084e-14,
       -4.19664303e-14, -4.14807078e-14])

In [32]:
cols = X.columns

X_squared = pd.concat((X, (X**2).rename(columns = {f'{var}' : f'{var}2' for var in cols })), axis = 1)
X_squared = sm.add_constant(X_squared)

X_squared.head()

   const    Sales  ...  Sub-Category_Supplies2  Sub-Category_Tables2
0    1.0   48.896  ...                       0                     0
1    1.0  474.430  ...                       0                     0
2    1.0    3.600  ...                       0                     0
3    1.0  454.560  ...                       0                     0
4    1.0  141.420  ...                       0                     0

[5 rows x 165 columns]

In [33]:
model.fit(X_squared, y)

model.coef_

array([ 3.28825368e-16,  2.13288194e-04,  5.80458807e-04,  7.56173135e-06,
        8.07818151e-05,  5.10326406e-06,  7.58159564e-07,  8.62428156e-06,
        1.98373056e-05,  3.09061501e-06, -1.07997517e-06, -2.01063984e-06,
       -1.94674017e-08,  5.24035496e-07,  1.58125040e-07,  4.38673551e-06,
        3.58614596e-07, -6.23800932e-07,  2.05691283e-07,  4.55424333e-08,
       -1.73557502e-06, -4.92834618e-07, -1.47110873e-07,  4.51665471e-07,
       -2.22191346e-07, -1.48422080e-07, -5.32308965e-08, -4.81253380e-07,
       -1.68841131e-07,  4.45171159e-08, -4.19451676e-07, -3.32184745e-07,
       -3.22993545e-07,  1.62348357e-07,  4.97450855e-08, -1.90047077e-07,
       -3.44697846e-07,  5.34287638e-08,  3.38572553e-07, -5.97099541e-07,
        3.70849899e-07, -5.64106053e-07,  2.80337190e-07,  1.90503048e-07,
        5.93593421e-07, -1.90233794e-07,  8.99389906e-08, -2.69545087e-07,
        3.39584853e-08,  1.70756108e-07, -1.69368635e-08,  2.73490943e-07,
       -3.21960211e-07,  1.18315037e-08, -3.49103749e-08, -1.60322072e-07,
       -7.05610975e-07,  2.06006132e-08, -2.52054361e-07, -7.23762013e-07,
       -1.19251173e-06, -2.45959517e-06,  4.37586891e-06, -6.39059807e-06,
        1.20049055e-05, -5.61430744e-06,  1.28357640e-06,  5.09886046e-07,
        3.52537147e-06,  6.79419046e-06, -9.50823710e-07, -4.23374670e-06,
       -1.47627661e-06,  5.32307938e-08,  9.13517409e-07,  3.29915115e-08,
        1.87086962e-06, -1.65785700e-06,  2.61415351e-06, -3.38430256e-06,
       -2.60334250e-06, -1.16159370e-06, -2.12984446e-06, -3.47635146e-08,
        5.82513372e-03,  4.71317466e-06,  6.85514672e-08,  5.10326407e-06,
        7.58159564e-07,  8.62428156e-06,  1.98373056e-05,  3.09061501e-06,
       -1.07997517e-06, -2.01063984e-06, -1.94674017e-08,  5.24035496e-07,
        1.58125040e-07,  4.38673551e-06,  3.58614596e-07, -6.23800932e-07,
        2.05691283e-07,  4.55424333e-08, -1.73557502e-06, -4.92834618e-07,
       -1.47110873e-07,  4.51665471e-07, -2.22191346e-07, -1.48422080e-07,
       -5.32308965e-08, -4.81253380e-07, -1.68841131e-07,  4.45171159e-08,
       -4.19451676e-07, -3.32184745e-07, -3.22993545e-07,  1.62348357e-07,
        4.97450855e-08, -1.90047077e-07, -3.44697846e-07,  5.34287638e-08,
        3.38572553e-07, -5.97099541e-07,  3.70849899e-07, -5.64106053e-07,
        2.80337190e-07,  1.90503048e-07,  5.93593421e-07, -1.90233794e-07,
        8.99389906e-08, -2.69545087e-07,  3.39584853e-08,  1.70756108e-07,
       -1.69368635e-08,  2.73490943e-07, -3.21960211e-07,  1.18315037e-08,
       -3.49103749e-08, -1.60322072e-07, -7.05610975e-07,  2.06006132e-08,
       -2.52054361e-07, -7.23762013e-07, -1.19251173e-06, -2.45959517e-06,
        4.37586891e-06, -6.39059807e-06,  1.20049055e-05, -5.61430744e-06,
        1.28357640e-06,  5.09886046e-07,  3.52537147e-06,  6.79419046e-06,
       -9.50823710e-07, -4.23374670e-06, -1.47627661e-06,  5.32307938e-08,
        9.13517409e-07,  3.29915115e-08,  1.87086962e-06, -1.65785700e-06,
        2.61415351e-06, -3.38430256e-06, -2.60334250e-06, -1.16159370e-06,
       -2.12984446e-06])

In [34]:
corr_3 = X_squared.corr(numeric_only = True)

upper_tri = corr_3.where(np.triu(np.ones(corr_3.shape), k = 1).astype(bool))

high_corr = upper_tri.stack().reset_index()
high_corr.columns = ['Variable 1', 'Variable 2', 'Correlation']

corr_tbl_3 = high_corr[high_corr['Correlation'].ge(0.8)]
corr_tbl_3 = corr_tbl_3.sort_values(by = ['Correlation'], ascending = False)

corr_tbl_3

                     Variable 1                 Variable 2  Correlation
912       Ship Mode_First Class     Ship Mode_First Class2     1.000000
2738             State_Colorado            State_Colorado2     1.000000
1078         Ship Mode_Same Day        Ship Mode_Same Day2     1.000000
1244     Ship Mode_Second Class    Ship Mode_Second Class2     1.000000
1410   Ship Mode_Standard Class  Ship Mode_Standard Class2     1.000000
...                         ...                        ...          ...
13196       Sub-Category_Phones       Sub-Category_Phones2     1.000000
13694       Sub-Category_Tables       Sub-Category_Tables2     1.000000
13781                    Sales2                    Profit2     0.931101
580                    Discount                  Discount2     0.928333
414                    Quantity                  Quantity2     0.913857

[81 rows x 3 columns]

Again, the highly correlated features are the ones that are squares of the regular features and the features that are similar or related.