In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import statsmodels.api as sm

from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split, RandomizedSearchCV

## Dataset 1: Instacart Analysis

In [2]:
data1 = pd.read_csv('https://raw.githubusercontent.com/eghatzis0527/DX699---HW-Assignments/refs/heads/main/instacart.csv')

transform_cols = ['times_purchased', 'num_orders', 'frequency', 'Product Popularity', 'Last Product Order', 'Last Order', 'Orders Since Last Purchase']

for col in transform_cols:
    data1[f'log_{col}'] = np.log1p(data1[col])

data1_transformed = data1.drop(columns = ['times_purchased', 'num_orders', 'frequency', 'Product Popularity', 'Last Product Order', 'Last Order', 'Orders Since Last Purchase'])

data1_transformed.head()

,user_id,product_id,ordered,log_times_purchased,log_num_orders,log_frequency,log_Product Popularity,log_Last Product Order,log_Last Order,log_Orders Since Last Purchase
0,71,45,0.0,1.791759,3.178054,0.196710,0.005878,2.302585,3.178054,2.708050
1,71,117,1.0,2.995732,3.178054,0.602175,0.001219,3.178054,3.178054,0.000000
2,71,2078,0.0,0.693147,3.178054,0.042560,0.006478,1.386294,3.178054,3.044522
3,71,2825,0.0,1.098612,3.178054,0.083382,0.003743,1.945910,3.178054,2.890372
4,71,3376,1.0,1.098612,3.178054,0.083382,0.003602,2.995732,3.178054,1.609438

In [3]:
X = data1_transformed.drop(columns = ['ordered'])
y = data1_transformed['ordered']

model = LinearRegression()

model.fit(X, y)

model.coef_

array([-1.85844815e-08,  3.30587125e-08,  8.43130152e-02,  1.22894456e-02,
        1.30557690e-02,  5.66384002e-04, -2.88704293e-02,  1.22894456e-02,
       -4.72387383e-02])

In [4]:
X.columns

Index(['user_id', 'product_id', 'log_times_purchased', 'log_num_orders',
       'log_frequency', 'log_Product Popularity', 'log_Last Product Order',
       'log_Last Order', 'log_Orders Since Last Purchase'],
      dtype='str')

In [5]:
cols = X.columns

X_squared = pd.concat((X, (X**2).rename(columns = {f'{var}' : f'{var}2' for var in cols })), axis = 1)
X_squared = sm.add_constant(X_squared)

X_squared.head()

,const,user_id,product_id,log_times_purchased,log_num_orders,log_frequency,log_Product Popularity,log_Last Product Order,log_Last Order,log_Orders Since Last Purchase,user_id2,product_id2,log_times_purchased2,log_num_orders2,log_frequency2,log_Product Popularity2,log_Last Product Order2,log_Last Order2,log_Orders Since Last Purchase2
0,1.0,71,45,1.791759,3.178054,0.196710,0.005878,2.302585,3.178054,2.708050,5041,2025,3.210402,10.100026,0.038695,0.000035,5.301898,10.100026,7.333536
1,1.0,71,117,2.995732,3.178054,0.602175,0.001219,3.178054,3.178054,0.000000,5041,13689,8.974412,10.100026,0.362615,0.000001,10.100026,10.100026,0.000000
2,1.0,71,2078,0.693147,3.178054,0.042560,0.006478,1.386294,3.178054,3.044522,5041,4318084,0.480453,10.100026,0.001811,0.000042,1.921812,10.100026,9.269117
3,1.0,71,2825,1.098612,3.178054,0.083382,0.003743,1.945910,3.178054,2.890372,5041,7980625,1.206949,10.100026,0.006952,0.000014,3.786566,10.100026,8.354249
4,1.0,71,3376,1.098612,3.178054,0.083382,0.003602,2.995732,3.178054,1.609438,5041,11397376,1.206949,10.100026,0.006952,0.000013,8.974412,10.100026,2.590290

In [6]:
model.fit(X_squared, y)

model.coef_

array([ 0.00000000e+00,  3.00413966e-09,  1.32794771e-13,  2.43269335e-16,
        1.16448815e-15,  7.02029677e-17, -3.12645606e-17,  1.23380940e-15,
        1.16448815e-15,  1.17773090e-15, -9.11942259e-14,  5.83359899e-13,
        1.29659474e-15,  9.86129203e-15,  6.94445174e-17, -1.85792939e-18,
        8.32757908e-15,  9.86129203e-15,  5.72834172e-15])

In [7]:
corr_1 = X_squared.corr(numeric_only = True)

upper_tri = corr_1.where(np.triu(np.ones(corr_1.shape), k = 1).astype(bool))

high_corr = upper_tri.stack().reset_index()
high_corr.columns = ['Variable 1', 'Variable 2', 'Correlation']

corr_tbl_1 = high_corr[high_corr['Correlation'].ge(0.8)]
corr_tbl_1 = corr_tbl_1.sort_values(by = ['Correlation'], ascending = False)

corr_tbl_1

,Variable 1,Variable 2,Correlation
84,log_num_orders,log_Last Order,1.000000
264,log_num_orders2,log_Last Order2,1.000000
89,log_num_orders,log_num_orders2,0.988527
93,log_num_orders,log_Last Order2,0.988527
165,log_Last Order,log_num_orders2,0.988527
169,log_Last Order,log_Last Order2,0.988527
149,log_Last Product Order,log_Last Product Order2,0.977488
69,log_times_purchased,log_times_purchased2,0.969256
29,user_id,user_id2,0.969009
49,product_id,product_id2,0.968813
189,log_Orders Since Last Purchase,log_Orders Since Last Purchase2,0.946289
109,log_frequency,log_frequency2,0.932337
129,log_Product Popularity,log_Product Popularity2,0.912437

Looking at these results, all of the squared values are highly correlated, but all the engineered features are also highly correlated. This is concerning due to multicollinearity. The engineered features might also be highly correlated since they are built in very similar ways

I am now going to perform hyperparameter tuning on the linear regression model to find the best model for my data. I will then construct a decile table that shows the lift for the model per decile.

In [8]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25)

params = {'copy_X' : [True, False], 'fit_intercept' : [True, False], 'n_jobs' : [5, 10, 15, None], 'positive' : [True, False]}

random_search = RandomizedSearchCV(model, params, n_iter = 32, cv = 5)
random_search.fit(X_train, y_train)

print(f"Best Hyperparameters: {random_search.best_params_}")

Best Hyperparameters: {'positive': True, 'n_jobs': 5, 'fit_intercept': True, 'copy_X': True}

In [9]:
best_model = LinearRegression(positive = True, n_jobs = 5, fit_intercept = True, copy_X = True)

best_model.fit(X_train, y_train)

y_preds = best_model.predict(X_test)

results = pd.DataFrame({'Predicted' : y_preds, 'Actual' : y_test})

results['decile'] = pd.qcut(results['Predicted'], q = 10, labels = False) + 1

lift_table = results.groupby('decile').agg(avg_predicted = ('Predicted', 'mean'), avg_ordered = ('Actual', 'mean'))

overall_ordered = np.mean(y_test)

lift_table['lift'] = lift_table['avg_ordered']/overall_ordered

lift_table['avg_predicted'] = lift_table['avg_predicted'].map(lambda x: f'{x:.3f}')
lift_table['avg_ordered'] = lift_table['avg_ordered'].map(lambda x: f'{x:.3f}')
lift_table['lift'] = lift_table['lift'].map(lambda x: f'{x:.3f}')

display(lift_table)

       avg_predicted avg_ordered   lift
decile
1             -0.013       0.007  0.111
2              0.008       0.010  0.162
3              0.019       0.016  0.255
4              0.026       0.031  0.496
5              0.034       0.033  0.531
6              0.045       0.041  0.654
7              0.061       0.059  0.940
8              0.085       0.074  1.183
9              0.122       0.108  1.726
10             0.232       0.248  3.942

Looking at this lift table, you can see there is a steady increase from the first to ninth decile, and then the lift more than doubles to the tenth decile. This shows the model does a great job at seperating the customers who are likely to order a product from those that are not.

However, you can notice for average predicted and ordered, the average is very low which is telling me most customers do not order products even in the top decile. This could be contributed to the large class imbalance.

## Dataset 2: Amazon Reviews Dataset

In [10]:
import ast
from sklearn.preprocessing import MultiLabelBinarizer

small_reviews = pd.read_csv('https://raw.githubusercontent.com/eghatzis0527/DX699---HW-Assignments/refs/heads/main/small_reviews%5B1%5D.csv')

small_meta = pd.read_csv('https://raw.githubusercontent.com/eghatzis0527/DX699---HW-Assignments/refs/heads/main/small_meta%5B1%5D.csv')

small_meta = small_meta.set_index(keys = 'parent_asin')

small_meta = small_meta.drop(columns = ['title', 'images'])

data2 = small_reviews.join(small_meta, on = 'parent_asin', how = 'inner')

data2 = data2.drop(columns = ['main_category', 'store', 'rating_number', 'videos', 'images', 'subtitle', 'author', 'bought_together', 'features', 'description', 'details', 'timestamp', 'text', 'title'])

data2['product_review_count'] = data2.groupby('asin').transform('size')
data2['user_review_count'] = data2.groupby('user_id').transform('size')

data2['price'] = data2['price'].fillna(data2['price'].median())

data2['categories'] = data2['categories'].apply(ast.literal_eval)

mlb = MultiLabelBinarizer()

categories = pd.DataFrame(mlb.fit_transform(data2['categories']), columns = mlb.classes_, index = data2.index)

top_30 = categories.sum().sort_values(ascending = False).head(31).index

categories = categories[top_30[1:31]]

data2 = data2.drop(columns = 'categories')

data2 = data2.join(categories)

columns_to_transform = ['helpful_vote', 'average_rating', 'price', 'product_review_count', 'user_review_count']

for col in columns_to_transform:
    data2[f'log_{col}'] = np.log1p(data2[col])

data2_transformed = data2.drop(columns = ['helpful_vote', 'average_rating', 'price', 'product_review_count', 'user_review_count'])

data2_transformed = data2_transformed.reset_index(drop = True)

for i in range(len(data2_transformed)):
    if data2_transformed.iloc[i]['rating'] == 4:
        data2_transformed.loc[i, 'liked'] = 1
    elif data2_transformed.iloc[i]['rating'] == 5:
        data2_transformed.loc[i, 'liked'] = 1
    else:
        data2_transformed.loc[i, 'liked'] = 0

X = data2_transformed.drop(columns = ['asin', 'parent_asin', 'user_id', 'liked', 'rating'])
y = data2_transformed['liked']

In [11]:
X.head()

,verified_purchase,Beverages,Snacks & Sweets,Pantry Staples,Coffee,Snack Foods,Candy & Chocolate,"Bottled Beverages, Water & Drink Mixes",Cooking & Baking,Breads & Bakery,...,Whole Coffee Beans,"Canned, Jarred & Packaged Foods",Cold Cereals,"Baking Syrups, Sugars & Sweeteners",Black,log_helpful_vote,log_average_rating,log_price,log_product_review_count,log_user_review_count
0,False,1,0,0,0,0,0,0,0,0,...,0,0,0,0,1,0.000000,1.704748,3.257712,0.693147,0.693147
1,True,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,3.295837,1.686399,3.351307,0.693147,0.693147
2,True,1,0,0,1,0,0,0,0,0,...,1,0,0,0,0,0.000000,1.686399,2.889816,0.693147,1.098612
3,True,0,0,1,0,0,0,0,1,0,...,0,0,0,0,0,0.000000,1.722767,2.771964,0.693147,1.098612
4,True,1,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0.000000,1.686399,3.395179,1.609438,0.693147

In [12]:
model.fit(X, y)

model.coef_

array([ 0.01500923, -0.05582391,  0.10519698, -0.0119624 , -0.13437413,
       -0.10918796, -0.15201427,  0.11096482,  0.08042212,  0.07291762,
        0.25489194, -0.07937857, -0.08282584,  0.01010096,  0.00132127,
       -0.18449217, -0.03364075, -0.03298354,  0.28827448,  0.05962195,
       -0.14470811,  0.25828544,  0.00150162,  0.00150162, -0.25135598,
        0.14819442,  0.14819442, -0.21591823,  0.12876094,  0.04783532,
        0.18256671, -0.0560935 ,  0.83537271, -0.0512716 ,  0.00726611,
        0.03929846])

In [13]:
cols = X.columns

X_squared = pd.concat((X, (X**2).rename(columns = {f'{var}' : f'{var}2' for var in cols })), axis = 1)
X_squared = sm.add_constant(X_squared)

X_squared.head()

,const,verified_purchase,Beverages,Snacks & Sweets,Pantry Staples,Coffee,Snack Foods,Candy & Chocolate,"Bottled Beverages, Water & Drink Mixes",Cooking & Baking,...,Whole Coffee Beans2,"Canned, Jarred & Packaged Foods2",Cold Cereals2,"Baking Syrups, Sugars & Sweeteners2",Black2,log_helpful_vote2,log_average_rating2,log_price2,log_product_review_count2,log_user_review_count2
0,1.0,False,1,0,0,0,0,0,0,0,...,0,0,0,0,1,0.000000,2.906166,10.612686,0.480453,0.480453
1,1.0,True,1,0,0,0,0,0,0,0,...,0,0,0,0,0,10.862541,2.843941,11.231256,0.480453,0.480453
2,1.0,True,1,0,0,1,0,0,0,0,...,1,0,0,0,0,0.000000,2.843941,8.351037,0.480453,1.206949
3,1.0,True,0,0,1,0,0,0,0,1,...,0,0,0,0,0,0.000000,2.967925,7.683782,0.480453,1.206949
4,1.0,True,1,0,0,1,0,0,0,0,...,0,0,0,0,0,0.000000,2.843941,11.527243,2.590290,0.480453

In [14]:
model.fit(X_squared, y)

model.coef_

array([ 1.59092825e-14, -3.90058670e-03, -2.25399860e-02,  4.64717327e-02,
       -8.72626998e-03, -6.68760767e-02, -5.19520940e-02, -7.63545433e-02,
        4.43047846e-02,  3.58481783e-02,  3.06023454e-02,  1.18644815e-01,
       -6.06934791e-02, -4.15314218e-02,  1.52856765e-02,  8.49728508e-04,
       -8.64149914e-02, -1.92390488e-02,  2.56749129e-03,  1.31941590e-01,
        2.98131514e-02, -7.68577912e-02,  1.39041088e-01,  7.78228398e-03,
        7.78228398e-03, -1.31627194e-01,  7.27296498e-02,  7.27296498e-02,
       -1.07307302e-01,  7.83546258e-02,  3.11527943e-02,  1.06271678e-01,
       -1.04807041e-01, -7.52135544e+00,  9.39279440e-02,  1.69913276e-01,
       -1.01357698e-01, -3.90058670e-03, -2.25399860e-02,  4.64717327e-02,
       -8.72626998e-03, -6.68760767e-02, -5.19520940e-02, -7.63545433e-02,
        4.43047846e-02,  3.58481783e-02,  3.06023454e-02,  1.18644815e-01,
       -6.06934791e-02, -4.15314218e-02,  1.52856765e-02,  8.49728508e-04,
       -8.64149914e-02, -1.92390488e-02,  2.56749129e-03,  1.31941590e-01,
        2.98131514e-02, -7.68577912e-02,  1.39041088e-01,  7.78228398e-03,
        7.78228398e-03, -1.31627194e-01,  7.27296498e-02,  7.27296498e-02,
       -1.07307302e-01,  7.83546258e-02,  3.11527943e-02,  1.06271678e-01,
        1.48064872e-02,  2.57753034e+00, -2.60086307e-02, -6.71174233e-02,
        3.16388570e-02])

In [15]:
corr_2 = X_squared.corr(numeric_only = True)

upper_tri = corr_2.where(np.triu(np.ones(corr_2.shape), k = 1).astype(bool))

high_corr = upper_tri.stack().reset_index()
high_corr.columns = ['Variable 1', 'Variable 2', 'Correlation']

corr_tbl_2 = high_corr[high_corr['Correlation'].ge(0.8)]
corr_tbl_2 = corr_tbl_2.sort_values(by = ['Correlation'], ascending = False)

corr_tbl_2

             Variable 1          Variable 2  Correlation
110   verified_purchase  verified_purchase2     1.000000
184           Beverages          Beverages2     1.000000
258     Snacks & Sweets    Snacks & Sweets2     1.000000
332      Pantry Staples     Pantry Staples2     1.000000
406              Coffee             Coffee2     1.000000
...                 ...                 ...          ...
743     Breads & Bakery             Cookies     0.850279
1598            Cereals       Cold Cereals2     0.812195
1562            Cereals        Cold Cereals     0.812195
2174       Cold Cereals            Cereals2     0.812195
4226           Cereals2       Cold Cereals2     0.812195

[64 rows x 3 columns]

Again, a lot of the highly correlated features are either features that are duplicates of themselves, the squared version of the feature or the regular features that are correlated. What would be the best move is to remove a lot of the duplicates, and then also figuring out which features should be squares and which should not to prevent multicollinearity.

I am now going to perform hyperparameter tuning to get the best model for this data as I did above. I am curious to see if the best parameters will be different based on this data, especially since a lot of the variables in this data are binary.

In [16]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25)

params = {'copy_X' : [True, False], 'fit_intercept' : [True, False], 'n_jobs' : [5, 10, 15, None], 'positive' : [True, False]}

random_search = RandomizedSearchCV(model, params, n_iter = 32, cv = 5)
random_search.fit(X_train, y_train)

print(f"Best Hyperparameters: {random_search.best_params_}")

Best Hyperparameters: {'positive': True, 'n_jobs': 5, 'fit_intercept': False, 'copy_X': True}

In [17]:
best_model = LinearRegression(positive = True, n_jobs = 5, fit_intercept = True, copy_X = True)

best_model.fit(X_train, y_train)

y_preds = best_model.predict(X_test)

results = pd.DataFrame({'Predicted' : y_preds, 'Actual' : y_test})

results['decile'] = pd.qcut(results['Predicted'], q = 10, labels = False) + 1

lift_table = results.groupby('decile').agg(avg_predicted = ('Predicted', 'mean'), avg_liked = ('Actual', 'mean'))

overall_liked = np.mean(y_test)

lift_table['lift'] = lift_table['avg_liked']/overall_liked

lift_table['avg_predicted'] = lift_table['avg_predicted'].map(lambda x: f'{x:.3f}')
lift_table['avg_liked'] = lift_table['avg_liked'].map(lambda x: f'{x:.3f}')
lift_table['lift'] = lift_table['lift'].map(lambda x: f'{x:.3f}')

display(lift_table)

       avg_predicted avg_liked   lift
decile
1              0.724     0.667  0.760
2              0.782     0.933  1.065
3              0.798     0.857  0.978
4              0.810     0.867  0.989
5              0.831     0.857  0.978
6              0.861     0.933  1.065
7              0.878     1.000  1.141
8              0.894     0.733  0.836
9              0.923     1.000  1.141
10             0.977     0.933  1.065

Looking at this lift table, you can see that from the third decile on, the lift stays the same at the rate of 1.197. This could be contributed to the fact that there is a large class imbalance where the majority of the customers like the data and therefore the deciles are only customers that liked the product.  

## Dataset 3: Ecommerce Dataset

In [18]:
data3 = pd.read_csv('/workspaces/DX799---HW-Assignments/data.csv', encoding = 'windows-1252')
data3['Purchased'] = 1

customer_id = data3['Customer ID'].values
segments = data3['Segment'].values
cities = data3['City'].values
state = data3['State'].values
region = data3['Region'].values
product_id = data3['Product ID'].values
categories = data3['Category'].values
subcategories = data3['Sub-Category'].values

def generate_row(df):
    row = {}

    row['Customer ID'] = np.random.choice(customer_id)
    cust_id = row['Customer ID']
    purchased = set(df[df['Customer ID'] == cust_id]['Product ID'])
    candidates = list(set(product_id) - purchased)

    row['Segment'] = np.random.choice(segments)
    row['State'] = np.random.choice(state)
    row['City'] = np.random.choice(cities)
    row['Region'] = np.random.choice(region)
    row['Product ID'] = np.random.choice(candidates)
    row['Category'] = np.random.choice(categories)
    row['Sub-Category'] = np.random.choice(subcategories)

    row['Sales'] = 0
    row['Discount'] = 0
    row['Quantity'] = 0
    row['Profit'] = 0
    row['Purchased'] = 0

    return row

fake_rows = pd.DataFrame([generate_row(data3) for n in range(1000)])

fake_df = pd.concat([data3, fake_rows], ignore_index = True)

fake_df = fake_df.drop(columns = ['Row ID', 'Product Name', 'Country', 'Postal Code', 'Order ID', 'Order Date'])

fake_df_encoded = pd.get_dummies(fake_df, columns = ['Ship Mode', 'Segment', 'State', 'Region', 'Category', 'Sub-Category'], dtype = int)

X = fake_df_encoded.drop(columns = ['Customer ID', 'Product ID', 'City', 'Purchased'])
y = fake_df_encoded['Purchased']

In [19]:
X.head()

,Sales,Quantity,Discount,Profit,Ship Mode_First Class,Ship Mode_Same Day,Ship Mode_Second Class,Ship Mode_Standard Class,Segment_Consumer,Segment_Corporate,...,Sub-Category_Envelopes,Sub-Category_Fasteners,Sub-Category_Furnishings,Sub-Category_Labels,Sub-Category_Machines,Sub-Category_Paper,Sub-Category_Phones,Sub-Category_Storage,Sub-Category_Supplies,Sub-Category_Tables
0,48.896,4,0.2,8.5568,0,0,0,1,1,0,...,0,0,1,0,0,0,0,0,0,0
1,474.430,11,0.0,199.2606,0,0,0,1,1,0,...,0,0,1,0,0,0,0,0,0,0
2,3.600,2,0.0,1.7280,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,454.560,5,0.2,-107.9580,0,0,0,1,1,0,...,0,0,0,0,0,0,0,1,0,0
4,141.420,5,0.6,-187.3815,0,0,0,1,1,0,...,0,0,1,0,0,0,0,0,0,0

In [20]:
model.fit(X, y)

model.coef_

array([ 5.31908392e-19, -1.04625510e-16,  6.10622664e-16, -9.71445147e-17,
        1.00000000e+00,  1.00000000e+00,  1.00000000e+00,  1.00000000e+00,
       -4.63518113e-15, -4.21884749e-15, -4.35762537e-15,  1.80411242e-15,
        2.22044605e-15,  6.38378239e-16,  7.77156117e-16, -5.27355937e-16,
        2.49800181e-16,  2.22044605e-16, -5.24580379e-15,  7.77156117e-16,
        8.88178420e-16,  9.99200722e-16, -5.68989300e-16,  1.02001740e-15,
        4.16333634e-16,  3.05311332e-16,  1.66533454e-16,  6.32306707e-16,
       -1.11022302e-16,  5.65519853e-16,  8.32667268e-17,  4.92661467e-16,
        8.60422844e-16,  8.25728375e-16, -1.53349555e-15,  1.23859256e-15,
        2.35922393e-16,  5.56846236e-16,  1.02695630e-15,  3.22658567e-16,
        3.05311332e-16,  3.69843045e-15,  1.08593690e-15, -3.88578059e-16,
        3.01841885e-16,  5.96744876e-16,  2.49800181e-16,  3.40005801e-16,
        2.28983499e-16,  1.76334641e-15,  4.02455846e-16, -1.11022302e-16,
        1.40165657e-15,  6.34908792e-16,  1.06858966e-15,  1.20736754e-15,
       -2.68882139e-16,  9.74914593e-16,  5.21804822e-15,  5.44009282e-15,
        4.49640325e-15,  4.77395901e-15,  0.00000000e+00, -1.66533454e-16,
       -2.77555756e-16,  9.57567359e-16,  3.88578059e-16,  6.10622664e-16,
        9.71445147e-17, -1.16573418e-15,  4.44089210e-16, -1.44328993e-15,
       -2.22044605e-15, -4.99600361e-16,  6.52256027e-16,  7.49400542e-16,
       -1.66533454e-15, -2.22044605e-16,  5.41233725e-16, -2.77555756e-17,
        4.16333634e-17, -3.26995375e-16])

In [21]:
cols = X.columns

X_squared = pd.concat((X, (X**2).rename(columns = {f'{var}' : f'{var}2' for var in cols })), axis = 1)
X_squared = sm.add_constant(X_squared)

X_squared.head()

,const,Sales,Quantity,Discount,Profit,Ship Mode_First Class,Ship Mode_Same Day,Ship Mode_Second Class,Ship Mode_Standard Class,Segment_Consumer,...,Sub-Category_Envelopes2,Sub-Category_Fasteners2,Sub-Category_Furnishings2,Sub-Category_Labels2,Sub-Category_Machines2,Sub-Category_Paper2,Sub-Category_Phones2,Sub-Category_Storage2,Sub-Category_Supplies2,Sub-Category_Tables2
0,1.0,48.896,4,0.2,8.5568,0,0,0,1,1,...,0,0,1,0,0,0,0,0,0,0
1,1.0,474.430,11,0.0,199.2606,0,0,0,1,1,...,0,0,1,0,0,0,0,0,0,0
2,1.0,3.600,2,0.0,1.7280,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,1.0,454.560,5,0.2,-107.9580,0,0,0,1,1,...,0,0,0,0,0,0,0,1,0,0
4,1.0,141.420,5,0.6,-187.3815,0,0,0,1,1,...,0,0,1,0,0,0,0,0,0,0

In [22]:
model.fit(X_squared, y)

model.coef_

array([ 3.28770633e-16,  2.13286494e-04,  5.80465611e-04,  7.56189659e-06,
        8.07806940e-05,  5.10335119e-06,  7.58178599e-07,  8.62451067e-06,
        1.98377580e-05,  4.01845897e-06, -1.04544337e-06, -2.97301560e-06,
       -8.81191162e-08, -2.50761304e-08,  8.95294018e-08,  4.59368656e-06,
        6.33320308e-07, -5.55178595e-07,  2.05644650e-07,  4.55367923e-08,
       -1.94143087e-06, -3.55472915e-07, -1.12787695e-07,  3.13889827e-07,
       -8.06015360e-07, -2.51374164e-07, -1.21890642e-07, -4.81288369e-07,
       -1.68816084e-07,  2.50460403e-07, -7.62224702e-08, -4.69601123e-07,
       -3.23055600e-07,  1.62384509e-07,  2.21361838e-07, -2.24379817e-07,
       -3.44659525e-07,  5.34295905e-08,  3.38573665e-07, -7.34472355e-07,
        3.70842334e-07,  1.56602183e-07,  3.49070320e-07,  8.74878381e-08,
        6.62234779e-07, -2.58941357e-07,  1.24287030e-07, -6.47583372e-07,
       -6.90614113e-08,  1.70752643e-07,  5.17114483e-08, -1.38459615e-07,
        1.24394663e-07, -5.67853023e-08, -6.02793790e-10, -4.34910578e-07,
       -2.93465853e-07,  2.05881330e-08, -4.61378040e-08, -1.72013905e-06,
       -1.77661095e-06, -1.97904574e-06,  5.47579574e-06, -7.38746246e-06,
        1.23492901e-05, -4.96182767e-06,  8.71578674e-07,  2.35132838e-07,
        3.42257621e-06,  8.06504089e-06, -8.13536662e-07, -4.37121452e-06,
       -1.47626915e-06, -3.24347501e-07,  1.05082256e-06, -7.57126753e-07,
        1.59630360e-06, -1.45199527e-06,  2.09907105e-06, -2.76608605e-06,
       -2.43170947e-06, -9.21219389e-07, -2.02702105e-06, -3.47632679e-08,
        5.82519186e-03,  4.71328067e-06,  6.85510543e-08,  5.10335118e-06,
        7.58178599e-07,  8.62451067e-06,  1.98377580e-05,  4.01845897e-06,
       -1.04544337e-06, -2.97301560e-06, -8.81191162e-08, -2.50761304e-08,
        8.95294018e-08,  4.59368656e-06,  6.33320308e-07, -5.55178595e-07,
        2.05644650e-07,  4.55367923e-08, -1.94143087e-06, -3.55472915e-07,
       -1.12787695e-07,  3.13889827e-07, -8.06015360e-07, -2.51374164e-07,
       -1.21890642e-07, -4.81288369e-07, -1.68816084e-07,  2.50460403e-07,
       -7.62224702e-08, -4.69601123e-07, -3.23055600e-07,  1.62384509e-07,
        2.21361838e-07, -2.24379817e-07, -3.44659525e-07,  5.34295905e-08,
        3.38573665e-07, -7.34472355e-07,  3.70842334e-07,  1.56602183e-07,
        3.49070320e-07,  8.74878381e-08,  6.62234779e-07, -2.58941357e-07,
        1.24287030e-07, -6.47583372e-07, -6.90614113e-08,  1.70752643e-07,
        5.17114483e-08, -1.38459615e-07,  1.24394663e-07, -5.67853023e-08,
       -6.02793790e-10, -4.34910578e-07, -2.93465853e-07,  2.05881330e-08,
       -4.61378040e-08, -1.72013905e-06, -1.77661095e-06, -1.97904574e-06,
        5.47579574e-06, -7.38746246e-06,  1.23492901e-05, -4.96182767e-06,
        8.71578674e-07,  2.35132838e-07,  3.42257621e-06,  8.06504089e-06,
       -8.13536662e-07, -4.37121452e-06, -1.47626915e-06, -3.24347501e-07,
        1.05082256e-06, -7.57126753e-07,  1.59630360e-06, -1.45199527e-06,
        2.09907105e-06, -2.76608605e-06, -2.43170947e-06, -9.21219389e-07,
       -2.02702105e-06])

In [23]:
corr_3 = X_squared.corr(numeric_only = True)

upper_tri = corr_3.where(np.triu(np.ones(corr_3.shape), k = 1).astype(bool))

high_corr = upper_tri.stack().reset_index()
high_corr.columns = ['Variable 1', 'Variable 2', 'Correlation']

corr_tbl_3 = high_corr[high_corr['Correlation'].ge(0.8)]
corr_tbl_3 = corr_tbl_3.sort_values(by = ['Correlation'], ascending = False)

corr_tbl_3

                     Variable 1                 Variable 2  Correlation
912       Ship Mode_First Class     Ship Mode_First Class2     1.000000
2738             State_Colorado            State_Colorado2     1.000000
1078         Ship Mode_Same Day        Ship Mode_Same Day2     1.000000
1244     Ship Mode_Second Class    Ship Mode_Second Class2     1.000000
1410   Ship Mode_Standard Class  Ship Mode_Standard Class2     1.000000
...                         ...                        ...          ...
13196       Sub-Category_Phones       Sub-Category_Phones2     1.000000
13694       Sub-Category_Tables       Sub-Category_Tables2     1.000000
13781                    Sales2                    Profit2     0.931101
580                    Discount                  Discount2     0.928333
414                    Quantity                  Quantity2     0.913857

[81 rows x 3 columns]

Again, the highly correlated features are the ones that are squares of the regular features and the features that are similar or related. I will now hyperparameter tune for the best model for this data and build a decile table to check performance. I am curious if the results will be similar to the second dataset since this model also has a smaller population size.

In [24]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25)

params = {'copy_X' : [True, False], 'fit_intercept' : [True, False], 'n_jobs' : [5, 10, 15, None], 'positive' : [True, False]}

random_search = RandomizedSearchCV(model, params, n_iter = 32, cv = 5)
random_search.fit(X_train, y_train)

print(f"Best Hyperparameters: {random_search.best_params_}")

Best Hyperparameters: {'positive': True, 'n_jobs': 5, 'fit_intercept': True, 'copy_X': True}

In [25]:
best_model = LinearRegression(positive = True, n_jobs = 5, fit_intercept = True, copy_X = True)

best_model.fit(X_train, y_train)

y_preds = best_model.predict(X_test)

results = pd.DataFrame({'Predicted' : y_preds, 'Actual' : y_test})

results['decile'] = pd.qcut(results['Predicted'].rank(method = 'first'), q = 10, labels = False) + 1

lift_table = results.groupby('decile').agg(avg_predicted = ('Predicted', 'mean'), avg_ordered = ('Actual', 'mean'))

overall_ordered = np.mean(y_test)

lift_table['lift'] = lift_table['avg_ordered']/overall_ordered

lift_table['avg_predicted'] = lift_table['avg_predicted'].map(lambda x: f'{x:.3f}')
lift_table['avg_ordered'] = lift_table['avg_ordered'].map(lambda x: f'{x:.3f}')
lift_table['lift'] = lift_table['lift'].map(lambda x: f'{x:.3f}')

display(lift_table)

       avg_predicted avg_ordered   lift
decile
1             -0.000       0.000  0.000
2             -0.000       0.000  0.000
3              0.537       0.537  0.713
4              1.000       1.000  1.328
5              1.000       1.000  1.328
6              1.000       1.000  1.328
7              1.000       1.000  1.328
8              1.000       1.000  1.328
9              1.000       1.000  1.328
10             1.000       1.000  1.328

Looking at the results, you can see the table has a similar result to the second datasets table where most of the deciles have the same lift due to the majority of the customers having ordered something.