# Homework 2: Ridge and Lasso Regression on Our Data

In this homework assignment, I will be performing ridge and lasso regression on my datasets. One thing to note is that all three of my datasets have binary targets, so analyzing the accuracy of them will be a lot harder. I will be constructing a decile based system that will look at the performance compared to the actual values.

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import statsmodels.api as sm

from sklearn.linear_model import Ridge, Lasso
from sklearn.model_selection import train_test_split, RandomizedSearchCV

## Dataset 1: Instacart Analysis

The first dataset I am using is one that looks at historical instacart orders. This dataset's main goal is predict whether or not someone will order a product. Below I will load in the dataset and also perform some feature engineering. The features I am creating are used to help predict how likely that product is ordered in that specific order.

In [2]:
data1 = pd.read_csv('https://raw.githubusercontent.com/eghatzis0527/DX699---HW-Assignments/refs/heads/main/instacart.csv')

transform_cols = ['times_purchased', 'num_orders', 'frequency', 'Product Popularity', 'Last Product Order', 'Last Order', 'Orders Since Last Purchase']

for col in transform_cols:
    data1[f'log_{col}'] = np.log1p(data1[col])

data1_transformed = data1.drop(columns = ['times_purchased', 'num_orders', 'frequency', 'Product Popularity', 'Last Product Order', 'Last Order', 'Orders Since Last Purchase'])

data1_transformed.head()

,user_id,product_id,ordered,log_times_purchased,log_num_orders,log_frequency,log_Product Popularity,log_Last Product Order,log_Last Order,log_Orders Since Last Purchase
0,71,45,0.0,1.791759,3.178054,0.196710,0.005878,2.302585,3.178054,2.708050
1,71,117,1.0,2.995732,3.178054,0.602175,0.001219,3.178054,3.178054,0.000000
2,71,2078,0.0,0.693147,3.178054,0.042560,0.006478,1.386294,3.178054,3.044522
3,71,2825,0.0,1.098612,3.178054,0.083382,0.003743,1.945910,3.178054,2.890372
4,71,3376,1.0,1.098612,3.178054,0.083382,0.003602,2.995732,3.178054,1.609438

In [3]:
X = data1_transformed.drop(columns = ['ordered'])
y = data1_transformed['ordered']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 42)

alphas = np.logspace(-4, 2, 100)
params = {'alpha' : alphas}

lasso = Lasso()

random_search = RandomizedSearchCV(lasso, params, cv = 5, n_iter = 100)

random_search.fit(X_train, y_train)

print(f'Best Alpha: {random_search.best_params_}')

Best Alpha: {'alpha': np.float64(0.0001)}

In [4]:
best_lasso = Lasso(alpha = 0.0001)

best_lasso.fit(X_train, y_train)

y_preds = best_lasso.predict(X_test)

values = {'Actual' : y_test, 'Predicted' : y_preds}

values = pd.DataFrame(values)

values.head()

        Actual  Predicted
281280     1.0   0.153056
38562      0.0   0.091176
220303     0.0   0.017768
211506     0.0   0.028532
321641     0.0   0.017597

In [5]:
values['Decile'] = pd.qcut(values['Predicted'], q = 10, labels = False) + 1

values.head()

        Actual  Predicted  Decile
281280     1.0   0.153056       9
38562      0.0   0.091176       8
220303     0.0   0.017768       4
211506     0.0   0.028532       5
321641     0.0   0.017597       4

In [6]:
decile_table = values.groupby('Decile').agg(avg_predicted = ('Predicted', 'mean'), avg_ordered = ('Actual', 'mean'))

overall_ordered = y_test.mean()

decile_table['lift'] = decile_table['avg_ordered']/overall_ordered

decile_table['avg_predicted'] = decile_table['avg_predicted'].map(lambda x: f'{x:.3f}')
decile_table['avg_ordered'] = decile_table['avg_ordered'].map(lambda x : f'{x:.3f}')
decile_table['lift'] = decile_table['lift'].map(lambda x: f'{x:.3f}')

decile_table

       avg_predicted avg_ordered   lift
Decile
1             -0.010       0.007  0.109
2             -0.001       0.008  0.129
3              0.008       0.017  0.267
4              0.018       0.020  0.312
5              0.030       0.030  0.478
6              0.047       0.046  0.724
7              0.068       0.053  0.839
8              0.091       0.079  1.237
9              0.127       0.119  1.871
10             0.235       0.257  4.034

In [7]:
ridge = Ridge()

random_search = RandomizedSearchCV(ridge, params, cv = 5, n_iter = 100)

random_search.fit(X_train, y_train)

print(f'Best Alpha: {random_search.best_params_}')

/usr/local/python/3.14.2/lib/python3.14/site-packages/sklearn/linear_model/_ridge.py:227: LinAlgWarning: An ill-conditioned matrix detected: slice 0 has rcond = 3.9751910817119536e-18.
  return linalg.solve(A, Xy, assume_a="pos", overwrite_a=True).T
/usr/local/python/3.14.2/lib/python3.14/site-packages/sklearn/linear_model/_ridge.py:227: LinAlgWarning: An ill-conditioned matrix detected: slice 0 has rcond = 3.977614821354073e-18.
  return linalg.solve(A, Xy, assume_a="pos", overwrite_a=True).T
/usr/local/python/3.14.2/lib/python3.14/site-packages/sklearn/linear_model/_ridge.py:227: LinAlgWarning: An ill-conditioned matrix detected: slice 0 has rcond = 3.9785210859748414e-18.
  return linalg.solve(A, Xy, assume_a="pos", overwrite_a=True).T
/usr/local/python/3.14.2/lib/python3.14/site-packages/sklearn/linear_model/_ridge.py:227: LinAlgWarning: An ill-conditioned matrix detected: slice 0 has rcond = 3.9823115214104235e-18.
  return linalg.solve(A, Xy, assume_a="pos", overwrite_a=True).T
/usr/local/python/3.14.2/lib/python3.14/site-packages/sklearn/linear_model/_ridge.py:227: LinAlgWarning: An ill-conditioned matrix detected: slice 0 has rcond = 3.978334816908024e-18.
  return linalg.solve(A, Xy, assume_a="pos", overwrite_a=True).T
/usr/local/python/3.14.2/lib/python3.14/site-packages/sklearn/linear_model/_ridge.py:227: LinAlgWarning: An ill-conditioned matrix detected: slice 0 has rcond = 4.570497927565067e-18.
  return linalg.solve(A, Xy, assume_a="pos", overwrite_a=True).T
/usr/local/python/3.14.2/lib/python3.14/site-packages/sklearn/linear_model/_ridge.py:227: LinAlgWarning: An ill-conditioned matrix detected: slice 0 has rcond = 4.573285853525705e-18.
  return linalg.solve(A, Xy, assume_a="pos", overwrite_a=True).T
/usr/local/python/3.14.2/lib/python3.14/site-packages/sklearn/linear_model/_ridge.py:227: LinAlgWarning: An ill-conditioned matrix detected: slice 0 has rcond = 4.574326718006163e-18.
  return linalg.solve(A, Xy, assume_a="pos", overwrite_a=True).T
/usr/local/python/3.14.2/lib/python3.14/site-packages/sklearn/linear_model/_ridge.py:227: LinAlgWarning: An ill-conditioned matrix detected: slice 0 has rcond = 4.5786853909164075e-18.
  return linalg.solve(A, Xy, assume_a="pos", overwrite_a=True).T
/usr/local/python/3.14.2/lib/python3.14/site-packages/sklearn/linear_model/_ridge.py:227: LinAlgWarning: An ill-conditioned matrix detected: slice 0 has rcond = 4.57411189494836e-18.
  return linalg.solve(A, Xy, assume_a="pos", overwrite_a=True).T
/usr/local/python/3.14.2/lib/python3.14/site-packages/sklearn/linear_model/_ridge.py:227: LinAlgWarning: An ill-conditioned matrix detected: slice 0 has rcond = 5.2549550679934465e-18.
  return linalg.solve(A, Xy, assume_a="pos", overwrite_a=True).T
/usr/local/python/3.14.2/lib/python3.14/site-packages/sklearn/linear_model/_ridge.py:227: LinAlgWarning: An ill-conditioned matrix detected: slice 0 has rcond = 5.25815922195101e-18.
  return linalg.solve(A, Xy, assume_a="pos", overwrite_a=True).T
/usr/local/python/3.14.2/lib/python3.14/site-packages/sklearn/linear_model/_ridge.py:227: LinAlgWarning: An ill-conditioned matrix detected: slice 0 has rcond = 5.25935792354062e-18.
  return linalg.solve(A, Xy, assume_a="pos", overwrite_a=True).T
/usr/local/python/3.14.2/lib/python3.14/site-packages/sklearn/linear_model/_ridge.py:227: LinAlgWarning: An ill-conditioned matrix detected: slice 0 has rcond = 5.264369270901839e-18.
  return linalg.solve(A, Xy, assume_a="pos", overwrite_a=True).T
/usr/local/python/3.14.2/lib/python3.14/site-packages/sklearn/linear_model/_ridge.py:227: LinAlgWarning: An ill-conditioned matrix detected: slice 0 has rcond = 5.259111516965737e-18.
  return linalg.solve(A, Xy, assume_a="pos", overwrite_a=True).T
/usr/local/python/3.14.2/lib/python3.14/site-packages/sklearn/linear_model/_ridge.py:227: LinAlgWarning: An ill-conditioned matrix detected: slice 0 has rcond = 6.041913213389443e-18.
  return linalg.solve(A, Xy, assume_a="pos", overwrite_a=True).T
/usr/local/python/3.14.2/lib/python3.14/site-packages/sklearn/linear_model/_ridge.py:227: LinAlgWarning: An ill-conditioned matrix detected: slice 0 has rcond = 6.0455978262054105e-18.
  return linalg.solve(A, Xy, assume_a="pos", overwrite_a=True).T
/usr/local/python/3.14.2/lib/python3.14/site-packages/sklearn/linear_model/_ridge.py:227: LinAlgWarning: An ill-conditioned matrix detected: slice 0 has rcond = 6.046975443123009e-18.
  return linalg.solve(A, Xy, assume_a="pos", overwrite_a=True).T
/usr/local/python/3.14.2/lib/python3.14/site-packages/sklearn/linear_model/_ridge.py:227: LinAlgWarning: An ill-conditioned matrix detected: slice 0 has rcond = 6.052736634372758e-18.
  return linalg.solve(A, Xy, assume_a="pos", overwrite_a=True).T
/usr/local/python/3.14.2/lib/python3.14/site-packages/sklearn/linear_model/_ridge.py:227: LinAlgWarning: An ill-conditioned matrix detected: slice 0 has rcond = 6.046691481483171e-18.
  return linalg.solve(A, Xy, assume_a="pos", overwrite_a=True).T
/usr/local/python/3.14.2/lib/python3.14/site-packages/sklearn/linear_model/_ridge.py:227: LinAlgWarning: An ill-conditioned matrix detected: slice 0 has rcond = 6.946720221260736e-18.
  return linalg.solve(A, Xy, assume_a="pos", overwrite_a=True).T
/usr/local/python/3.14.2/lib/python3.14/site-packages/sklearn/linear_model/_ridge.py:227: LinAlgWarning: An ill-conditioned matrix detected: slice 0 has rcond = 6.950956562451317e-18.
  return linalg.solve(A, Xy, assume_a="pos", overwrite_a=True).T
/usr/local/python/3.14.2/lib/python3.14/site-packages/sklearn/linear_model/_ridge.py:227: LinAlgWarning: An ill-conditioned matrix detected: slice 0 has rcond = 6.952541154251891e-18.
  return linalg.solve(A, Xy, assume_a="pos", overwrite_a=True).T
/usr/local/python/3.14.2/lib/python3.14/site-packages/sklearn/linear_model/_ridge.py:227: LinAlgWarning: An ill-conditioned matrix detected: slice 0 has rcond = 6.959164578457733e-18.
  return linalg.solve(A, Xy, assume_a="pos", overwrite_a=True).T
/usr/local/python/3.14.2/lib/python3.14/site-packages/sklearn/linear_model/_ridge.py:227: LinAlgWarning: An ill-conditioned matrix detected: slice 0 has rcond = 6.952214682800023e-18.
  return linalg.solve(A, Xy, assume_a="pos", overwrite_a=True).T
/usr/local/python/3.14.2/lib/python3.14/site-packages/sklearn/linear_model/_ridge.py:227: LinAlgWarning: An ill-conditioned matrix detected: slice 0 has rcond = 7.987024692822569e-18.
  return linalg.solve(A, Xy, assume_a="pos", overwrite_a=True).T
/usr/local/python/3.14.2/lib/python3.14/site-packages/sklearn/linear_model/_ridge.py:227: LinAlgWarning: An ill-conditioned matrix detected: slice 0 has rcond = 7.991895365669284e-18.
  return linalg.solve(A, Xy, assume_a="pos", overwrite_a=True).T
/usr/local/python/3.14.2/lib/python3.14/site-packages/sklearn/linear_model/_ridge.py:227: LinAlgWarning: An ill-conditioned matrix detected: slice 0 has rcond = 7.993716712109492e-18.
  return linalg.solve(A, Xy, assume_a="pos", overwrite_a=True).T
/usr/local/python/3.14.2/lib/python3.14/site-packages/sklearn/linear_model/_ridge.py:227: LinAlgWarning: An ill-conditioned matrix detected: slice 0 has rcond = 8.00133275002703e-18.
  return linalg.solve(A, Xy, assume_a="pos", overwrite_a=True).T
/usr/local/python/3.14.2/lib/python3.14/site-packages/sklearn/linear_model/_ridge.py:227: LinAlgWarning: An ill-conditioned matrix detected: slice 0 has rcond = 7.993341369734766e-18.
  return linalg.solve(A, Xy, assume_a="pos", overwrite_a=True).T
/usr/local/python/3.14.2/lib/python3.14/site-packages/sklearn/linear_model/_ridge.py:227: LinAlgWarning: An ill-conditioned matrix detected: slice 0 has rcond = 9.183117138019687e-18.
  return linalg.solve(A, Xy, assume_a="pos", overwrite_a=True).T
/usr/local/python/3.14.2/lib/python3.14/site-packages/sklearn/linear_model/_ridge.py:227: LinAlgWarning: An ill-conditioned matrix detected: slice 0 has rcond = 9.18871653037627e-18.
  return linalg.solve(A, Xy, assume_a="pos", overwrite_a=True).T
/usr/local/python/3.14.2/lib/python3.14/site-packages/sklearn/linear_model/_ridge.py:227: LinAlgWarning: An ill-conditioned matrix detected: slice 0 has rcond = 9.190810790175437e-18.
  return linalg.solve(A, Xy, assume_a="pos", overwrite_a=True).T
/usr/local/python/3.14.2/lib/python3.14/site-packages/sklearn/linear_model/_ridge.py:227: LinAlgWarning: An ill-conditioned matrix detected: slice 0 has rcond = 9.199568020179774e-18.
  return linalg.solve(A, Xy, assume_a="pos", overwrite_a=True).T
/usr/local/python/3.14.2/lib/python3.14/site-packages/sklearn/linear_model/_ridge.py:227: LinAlgWarning: An ill-conditioned matrix detected: slice 0 has rcond = 9.190380422501756e-18.
  return linalg.solve(A, Xy, assume_a="pos", overwrite_a=True).T
/usr/local/python/3.14.2/lib/python3.14/site-packages/sklearn/linear_model/_ridge.py:227: LinAlgWarning: An ill-conditioned matrix detected: slice 0 has rcond = 1.0558326630928305e-17.
  return linalg.solve(A, Xy, assume_a="pos", overwrite_a=True).T
/usr/local/python/3.14.2/lib/python3.14/site-packages/sklearn/linear_model/_ridge.py:227: LinAlgWarning: An ill-conditioned matrix detected: slice 0 has rcond = 1.0564765079853195e-17.
  return linalg.solve(A, Xy, assume_a="pos", overwrite_a=True).T
/usr/local/python/3.14.2/lib/python3.14/site-packages/sklearn/linear_model/_ridge.py:227: LinAlgWarning: An ill-conditioned matrix detected: slice 0 has rcond = 1.0567174331551426e-17.
  return linalg.solve(A, Xy, assume_a="pos", overwrite_a=True).T
/usr/local/python/3.14.2/lib/python3.14/site-packages/sklearn/linear_model/_ridge.py:227: LinAlgWarning: An ill-conditioned matrix detected: slice 0 has rcond = 1.0577240692331622e-17.
  return linalg.solve(A, Xy, assume_a="pos", overwrite_a=True).T
/usr/local/python/3.14.2/lib/python3.14/site-packages/sklearn/linear_model/_ridge.py:227: LinAlgWarning: An ill-conditioned matrix detected: slice 0 has rcond = 1.0566677638785078e-17.
  return linalg.solve(A, Xy, assume_a="pos", overwrite_a=True).T
/usr/local/python/3.14.2/lib/python3.14/site-packages/sklearn/linear_model/_ridge.py:227: LinAlgWarning: An ill-conditioned matrix detected: slice 0 has rcond = 1.2139475255796506e-17.
  return linalg.solve(A, Xy, assume_a="pos", overwrite_a=True).T
/usr/local/python/3.14.2/lib/python3.14/site-packages/sklearn/linear_model/_ridge.py:227: LinAlgWarning: An ill-conditioned matrix detected: slice 0 has rcond = 1.2146877121292493e-17.
  return linalg.solve(A, Xy, assume_a="pos", overwrite_a=True).T
/usr/local/python/3.14.2/lib/python3.14/site-packages/sklearn/linear_model/_ridge.py:227: LinAlgWarning: An ill-conditioned matrix detected: slice 0 has rcond = 1.2149646113431577e-17.
  return linalg.solve(A, Xy, assume_a="pos", overwrite_a=True).T
/usr/local/python/3.14.2/lib/python3.14/site-packages/sklearn/linear_model/_ridge.py:227: LinAlgWarning: An ill-conditioned matrix detected: slice 0 has rcond = 1.2161222661225304e-17.
  return linalg.solve(A, Xy, assume_a="pos", overwrite_a=True).T
/usr/local/python/3.14.2/lib/python3.14/site-packages/sklearn/linear_model/_ridge.py:227: LinAlgWarning: An ill-conditioned matrix detected: slice 0 has rcond = 1.2149075750281466e-17.
  return linalg.solve(A, Xy, assume_a="pos", overwrite_a=True).T
/usr/local/python/3.14.2/lib/python3.14/site-packages/sklearn/linear_model/_ridge.py:227: LinAlgWarning: An ill-conditioned matrix detected: slice 0 has rcond = 1.3957399581110018e-17.
  return linalg.solve(A, Xy, assume_a="pos", overwrite_a=True).T
/usr/local/python/3.14.2/lib/python3.14/site-packages/sklearn/linear_model/_ridge.py:227: LinAlgWarning: An ill-conditioned matrix detected: slice 0 has rcond = 1.3965909739523243e-17.
  return linalg.solve(A, Xy, assume_a="pos", overwrite_a=True).T
/usr/local/python/3.14.2/lib/python3.14/site-packages/sklearn/linear_model/_ridge.py:227: LinAlgWarning: An ill-conditioned matrix detected: slice 0 has rcond = 1.3969094342586675e-17.
  return linalg.solve(A, Xy, assume_a="pos", overwrite_a=True).T
/usr/local/python/3.14.2/lib/python3.14/site-packages/sklearn/linear_model/_ridge.py:227: LinAlgWarning: An ill-conditioned matrix detected: slice 0 has rcond = 1.3982404028249847e-17.
  return linalg.solve(A, Xy, assume_a="pos", overwrite_a=True).T
/usr/local/python/3.14.2/lib/python3.14/site-packages/sklearn/linear_model/_ridge.py:227: LinAlgWarning: An ill-conditioned matrix detected: slice 0 has rcond = 1.3968438625908133e-17.
  return linalg.solve(A, Xy, assume_a="pos", overwrite_a=True).T
/usr/local/python/3.14.2/lib/python3.14/site-packages/sklearn/linear_model/_ridge.py:227: LinAlgWarning: An ill-conditioned matrix detected: slice 0 has rcond = 1.6047556491420353e-17.
  return linalg.solve(A, Xy, assume_a="pos", overwrite_a=True).T
/usr/local/python/3.14.2/lib/python3.14/site-packages/sklearn/linear_model/_ridge.py:227: LinAlgWarning: An ill-conditioned matrix detected: slice 0 has rcond = 1.605734198695894e-17.
  return linalg.solve(A, Xy, assume_a="pos", overwrite_a=True).T
/usr/local/python/3.14.2/lib/python3.14/site-packages/sklearn/linear_model/_ridge.py:227: LinAlgWarning: An ill-conditioned matrix detected: slice 0 has rcond = 1.60610033121094e-17.
  return linalg.solve(A, Xy, assume_a="pos", overwrite_a=True).T
/usr/local/python/3.14.2/lib/python3.14/site-packages/sklearn/linear_model/_ridge.py:227: LinAlgWarning: An ill-conditioned matrix detected: slice 0 has rcond = 1.6076305815957966e-17.
  return linalg.solve(A, Xy, assume_a="pos", overwrite_a=True).T
/usr/local/python/3.14.2/lib/python3.14/site-packages/sklearn/linear_model/_ridge.py:227: LinAlgWarning: An ill-conditioned matrix detected: slice 0 has rcond = 1.6060248900765097e-17.
  return linalg.solve(A, Xy, assume_a="pos", overwrite_a=True).T
/usr/local/python/3.14.2/lib/python3.14/site-packages/sklearn/linear_model/_ridge.py:227: LinAlgWarning: An ill-conditioned matrix detected: slice 0 has rcond = 1.845070871818798e-17.
  return linalg.solve(A, Xy, assume_a="pos", overwrite_a=True).T
/usr/local/python/3.14.2/lib/python3.14/site-packages/sklearn/linear_model/_ridge.py:227: LinAlgWarning: An ill-conditioned matrix detected: slice 0 has rcond = 1.8461959093401473e-17.
  return linalg.solve(A, Xy, assume_a="pos", overwrite_a=True).T
/usr/local/python/3.14.2/lib/python3.14/site-packages/sklearn/linear_model/_ridge.py:227: LinAlgWarning: An ill-conditioned matrix detected: slice 0 has rcond = 1.846616877095113e-17.
  return linalg.solve(A, Xy, assume_a="pos", overwrite_a=True).T
/usr/local/python/3.14.2/lib/python3.14/site-packages/sklearn/linear_model/_ridge.py:227: LinAlgWarning: An ill-conditioned matrix detected: slice 0 has rcond = 1.8483763253467506e-17.
  return linalg.solve(A, Xy, assume_a="pos", overwrite_a=True).T
/usr/local/python/3.14.2/lib/python3.14/site-packages/sklearn/linear_model/_ridge.py:227: LinAlgWarning: An ill-conditioned matrix detected: slice 0 has rcond = 1.8465302734710148e-17.
  return linalg.solve(A, Xy, assume_a="pos", overwrite_a=True).T
/usr/local/python/3.14.2/lib/python3.14/site-packages/sklearn/linear_model/_ridge.py:227: LinAlgWarning: An ill-conditioned matrix detected: slice 0 has rcond = 2.1213723578007752e-17.
  return linalg.solve(A, Xy, assume_a="pos", overwrite_a=True).T
/usr/local/python/3.14.2/lib/python3.14/site-packages/sklearn/linear_model/_ridge.py:227: LinAlgWarning: An ill-conditioned matrix detected: slice 0 has rcond = 2.1226658054371468e-17.
  return linalg.solve(A, Xy, assume_a="pos", overwrite_a=True).T
/usr/local/python/3.14.2/lib/python3.14/site-packages/sklearn/linear_model/_ridge.py:227: LinAlgWarning: An ill-conditioned matrix detected: slice 0 has rcond = 2.1231499069876626e-17.
  return linalg.solve(A, Xy, assume_a="pos", overwrite_a=True).T
/usr/local/python/3.14.2/lib/python3.14/site-packages/sklearn/linear_model/_ridge.py:227: LinAlgWarning: An ill-conditioned matrix detected: slice 0 has rcond = 2.1251730006320104e-17.
  return linalg.solve(A, Xy, assume_a="pos", overwrite_a=True).T
/usr/local/python/3.14.2/lib/python3.14/site-packages/sklearn/linear_model/_ridge.py:227: LinAlgWarning: An ill-conditioned matrix detected: slice 0 has rcond = 2.1230502238234172e-17.
  return linalg.solve(A, Xy, assume_a="pos", overwrite_a=True).T
/usr/local/python/3.14.2/lib/python3.14/site-packages/sklearn/linear_model/_ridge.py:227: LinAlgWarning: An ill-conditioned matrix detected: slice 0 has rcond = 2.439048486348737e-17.
  return linalg.solve(A, Xy, assume_a="pos", overwrite_a=True).T
/usr/local/python/3.14.2/lib/python3.14/site-packages/sklearn/linear_model/_ridge.py:227: LinAlgWarning: An ill-conditioned matrix detected: slice 0 has rcond = 2.440535428532462e-17.
  return linalg.solve(A, Xy, assume_a="pos", overwrite_a=True).T
/usr/local/python/3.14.2/lib/python3.14/site-packages/sklearn/linear_model/_ridge.py:227: LinAlgWarning: An ill-conditioned matrix detected: slice 0 has rcond = 2.441092202957913e-17.
  return linalg.solve(A, Xy, assume_a="pos", overwrite_a=True).T
/usr/local/python/3.14.2/lib/python3.14/site-packages/sklearn/linear_model/_ridge.py:227: LinAlgWarning: An ill-conditioned matrix detected: slice 0 has rcond = 2.4434182435423275e-17.
  return linalg.solve(A, Xy, assume_a="pos", overwrite_a=True).T
/usr/local/python/3.14.2/lib/python3.14/site-packages/sklearn/linear_model/_ridge.py:227: LinAlgWarning: An ill-conditioned matrix detected: slice 0 has rcond = 2.4409776192553114e-17.
  return linalg.solve(A, Xy, assume_a="pos", overwrite_a=True).T
/usr/local/python/3.14.2/lib/python3.14/site-packages/sklearn/linear_model/_ridge.py:227: LinAlgWarning: An ill-conditioned matrix detected: slice 0 has rcond = 2.8042942687353764e-17.
  return linalg.solve(A, Xy, assume_a="pos", overwrite_a=True).T
/usr/local/python/3.14.2/lib/python3.14/site-packages/sklearn/linear_model/_ridge.py:227: LinAlgWarning: An ill-conditioned matrix detected: slice 0 has rcond = 2.8060037887301165e-17.
  return linalg.solve(A, Xy, assume_a="pos", overwrite_a=True).T
/usr/local/python/3.14.2/lib/python3.14/site-packages/sklearn/linear_model/_ridge.py:227: LinAlgWarning: An ill-conditioned matrix detected: slice 0 has rcond = 2.806644087779897e-17.
  return linalg.solve(A, Xy, assume_a="pos", overwrite_a=True).T
/usr/local/python/3.14.2/lib/python3.14/site-packages/sklearn/linear_model/_ridge.py:227: LinAlgWarning: An ill-conditioned matrix detected: slice 0 has rcond = 2.809318523684311e-17.
  return linalg.solve(A, Xy, assume_a="pos", overwrite_a=True).T
/usr/local/python/3.14.2/lib/python3.14/site-packages/sklearn/linear_model/_ridge.py:227: LinAlgWarning: An ill-conditioned matrix detected: slice 0 has rcond = 2.806512436091402e-17.
  return linalg.solve(A, Xy, assume_a="pos", overwrite_a=True).T
/usr/local/python/3.14.2/lib/python3.14/site-packages/sklearn/linear_model/_ridge.py:227: LinAlgWarning: An ill-conditioned matrix detected: slice 0 has rcond = 3.224231969406608e-17.
  return linalg.solve(A, Xy, assume_a="pos", overwrite_a=True).T
/usr/local/python/3.14.2/lib/python3.14/site-packages/sklearn/linear_model/_ridge.py:227: LinAlgWarning: An ill-conditioned matrix detected: slice 0 has rcond = 3.226197421901882e-17.
  return linalg.solve(A, Xy, assume_a="pos", overwrite_a=True).T
/usr/local/python/3.14.2/lib/python3.14/site-packages/sklearn/linear_model/_ridge.py:227: LinAlgWarning: An ill-conditioned matrix detected: slice 0 has rcond = 3.2269338581162215e-17.
  return linalg.solve(A, Xy, assume_a="pos", overwrite_a=True).T
/usr/local/python/3.14.2/lib/python3.14/site-packages/sklearn/linear_model/_ridge.py:227: LinAlgWarning: An ill-conditioned matrix detected: slice 0 has rcond = 3.230008881481043e-17.
  return linalg.solve(A, Xy, assume_a="pos", overwrite_a=True).T
/usr/local/python/3.14.2/lib/python3.14/site-packages/sklearn/linear_model/_ridge.py:227: LinAlgWarning: An ill-conditioned matrix detected: slice 0 has rcond = 3.226782523937843e-17.
  return linalg.solve(A, Xy, assume_a="pos", overwrite_a=True).T

Best Alpha: {'alpha': np.float64(0.1873817422860385)}

In [8]:
best_model = Ridge(alpha = random_search.best_params_['alpha'])

best_model.fit(X_train, y_train)

y_preds = best_model.predict(X_test)

values = {'Actual' : y_test, 'Predicted' : y_preds}

values = pd.DataFrame(values)

values['Decile'] = pd.qcut(values['Predicted'], q = 10, labels = False) + 1

decile_table = values.groupby('Decile').agg(avg_predicted = ('Predicted', 'mean'), avg_ordered = ('Actual', 'mean'))

overall_ordered = y_test.mean()

decile_table['lift'] = decile_table['avg_ordered']/overall_ordered

decile_table['avg_predicted'] = decile_table['avg_predicted'].map(lambda x: f'{x:.3f}')
decile_table['avg_ordered'] = decile_table['avg_ordered'].map(lambda x : f'{x:.3f}')
decile_table['lift'] = decile_table['lift'].map(lambda x: f'{x:.3f}')

decile_table

       avg_predicted avg_ordered   lift
Decile
1             -0.010       0.007  0.107
2             -0.001       0.010  0.160
3              0.007       0.017  0.261
4              0.017       0.019  0.297
5              0.030       0.031  0.486
6              0.046       0.043  0.679
7              0.067       0.055  0.870
8              0.091       0.076  1.202
9              0.128       0.120  1.894
10             0.239       0.257  4.044

In [9]:
# Looking at Class Imbalance

y_test.value_counts()

ordered
0.0    75484
1.0     5126
Name: count, dtype: int64

Comparing the two results, the ridge regression performed much better than the lasso regression. It can be seen that the lasso regression lift is pretty uniform for all ten deciles, unlike the ridge regression, which has a steady increase. You can see there is a massive jump in lift from the ninth to the tenth decile which could be due to the large class imbalance.

## Dataset 2: Amazon Reviews Dataset

The second dataset I am using looks into amazon reviews based on products that the platform sells. Due to the large amount of products on Amazon, I am specifically focusing on the grocery items sold on Amazon. I also will be selecting the top 30 categories of products due to the large amount of products as well.

In [10]:
import ast
from sklearn.preprocessing import MultiLabelBinarizer

small_reviews = pd.read_csv('https://raw.githubusercontent.com/eghatzis0527/DX699---HW-Assignments/refs/heads/main/small_reviews%5B1%5D.csv')

small_meta = pd.read_csv('https://raw.githubusercontent.com/eghatzis0527/DX699---HW-Assignments/refs/heads/main/small_meta%5B1%5D.csv')

small_meta = small_meta.set_index(keys = 'parent_asin')

small_meta = small_meta.drop(columns = ['title', 'images'])

data2 = small_reviews.join(small_meta, on = 'parent_asin', how = 'inner')

data2 = data2.drop(columns = ['main_category', 'store', 'rating_number', 'videos', 'images', 'subtitle', 'author', 'bought_together', 'features', 'description', 'details', 'timestamp', 'text', 'title'])

data2['product_review_count'] = data2.groupby('asin').transform('size')
data2['user_review_count'] = data2.groupby('user_id').transform('size')

data2['price'] = data2['price'].fillna(data2['price'].median())

data2['categories'] = data2['categories'].apply(ast.literal_eval)

mlb = MultiLabelBinarizer()

categories = pd.DataFrame(mlb.fit_transform(data2['categories']), columns = mlb.classes_, index = data2.index)

top_30 = categories.sum().sort_values(ascending = False).head(31).index

categories = categories[top_30[1:31]]

data2 = data2.drop(columns = 'categories')

data2 = data2.join(categories)

columns_to_transform = ['helpful_vote', 'average_rating', 'price', 'product_review_count', 'user_review_count']

for col in columns_to_transform:
    data2[f'log_{col}'] = np.log1p(data2[col])

data2_transformed = data2.drop(columns = ['helpful_vote', 'average_rating', 'price', 'product_review_count', 'user_review_count'])

data2_transformed = data2_transformed.reset_index(drop = True)

for i in range(len(data2_transformed)):
    if data2_transformed.iloc[i]['rating'] == 4:
        data2_transformed.loc[i, 'liked'] = 1
    elif data2_transformed.iloc[i]['rating'] == 5:
        data2_transformed.loc[i, 'liked'] = 1
    else:
        data2_transformed.loc[i, 'liked'] = 0

X = data2_transformed.drop(columns = ['asin', 'parent_asin', 'user_id', 'liked', 'rating'])
y = data2_transformed['liked']

X.head()

,verified_purchase,Beverages,Snacks & Sweets,Pantry Staples,Coffee,Snack Foods,Candy & Chocolate,"Bottled Beverages, Water & Drink Mixes",Cooking & Baking,Breads & Bakery,...,Whole Coffee Beans,"Canned, Jarred & Packaged Foods",Cold Cereals,"Baking Syrups, Sugars & Sweeteners",Black,log_helpful_vote,log_average_rating,log_price,log_product_review_count,log_user_review_count
0,False,1,0,0,0,0,0,0,0,0,...,0,0,0,0,1,0.000000,1.704748,3.257712,0.693147,0.693147
1,True,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,3.295837,1.686399,3.351307,0.693147,0.693147
2,True,1,0,0,1,0,0,0,0,0,...,1,0,0,0,0,0.000000,1.686399,2.889816,0.693147,1.098612
3,True,0,0,1,0,0,0,0,1,0,...,0,0,0,0,0,0.000000,1.722767,2.771964,0.693147,1.098612
4,True,1,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0.000000,1.686399,3.395179,1.609438,0.693147

In [11]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 42)

lasso = Lasso()

random_search = RandomizedSearchCV(lasso, params, cv = 5, n_iter = 100)

random_search.fit(X_train, y_train)

print(f'Best Hyperparameters: {random_search.best_params_}')

Best Hyperparameters: {'alpha': np.float64(0.03511191734215131)}

In [12]:
best_model = Lasso(alpha = 0.0001)

best_model.fit(X_train, y_train)

y_preds = best_model.predict(X_test)

values = {'Actual' : y_test, 'Predicted' : y_preds}

values = pd.DataFrame(values)

values['Decile'] = pd.qcut(values['Predicted'].rank(method = 'first'), q = 10, labels = False) + 1

decile_table = values.groupby('Decile').agg(avg_predicted = ('Predicted', 'mean'), avg_ordered = ('Actual', 'mean'))

overall_ordered = y_test.mean()

decile_table['lift'] = decile_table['avg_ordered']/overall_ordered

decile_table['avg_predicted'] = decile_table['avg_predicted'].map(lambda x: f'{x:.3f}')
decile_table['avg_ordered'] = decile_table['avg_ordered'].map(lambda x : f'{x:.3f}')
decile_table['lift'] = decile_table['lift'].map(lambda x: f'{x:.3f}')

decile_table

       avg_predicted avg_ordered   lift
Decile
1              0.674       0.667  0.798
2              0.764       0.600  0.718
3              0.812       0.929  1.111
4              0.847       0.867  1.037
5              0.872       0.929  1.111
6              0.895       0.933  1.117
7              0.923       0.786  0.940
8              0.951       0.867  1.037
9              0.984       0.929  1.111
10             1.056       0.867  1.037

In [13]:
ridge = Ridge()

random_search = RandomizedSearchCV(ridge, params, cv = 5, n_iter = 100)

random_search.fit(X_train, y_train)

print(f'Best Hyperparameters: {random_search.best_params_}')

Best Hyperparameters: {'alpha': np.float64(100.0)}

In [14]:
best_model = Ridge(alpha = random_search.best_params_['alpha'])

best_model.fit(X_train, y_train)

y_preds = best_model.predict(X_test)

values = {'Actual' : y_test, 'Predicted' : y_preds}

values = pd.DataFrame(values)

values['Decile'] = pd.qcut(values['Predicted'], q = 10, labels = False) + 1

decile_table = values.groupby('Decile').agg(avg_predicted = ('Predicted', 'mean'), avg_ordered = ('Actual', 'mean'))

overall_ordered = y_test.mean()

decile_table['lift'] = decile_table['avg_ordered']/overall_ordered

decile_table['avg_predicted'] = decile_table['avg_predicted'].map(lambda x: f'{x:.3f}')
decile_table['avg_ordered'] = decile_table['avg_ordered'].map(lambda x : f'{x:.3f}')
decile_table['lift'] = decile_table['lift'].map(lambda x: f'{x:.3f}')

decile_table

       avg_predicted avg_ordered   lift
Decile
1              0.806       0.667  0.798
2              0.832       0.867  1.037
3              0.844       0.643  0.769
4              0.857       0.800  0.957
5              0.867       0.857  1.026
6              0.879       0.933  1.117
7              0.886       0.929  1.111
8              0.896       0.867  1.037
9              0.911       0.857  1.026
10             0.940       0.933  1.117

In [15]:
# Looking at Class Imbalance

y.value_counts()

liked
1.0    502
0.0     81
Name: count, dtype: int64

Comparing the results between the two regression methods showed that overall, both models performed very similarly, with ridge regression having a slighlty better performance in the top decile.